learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),#分层次  users的层次
    path('', include('learning_logs.urls')),#分层次  ‘’的层次
]

learning_logs/urls.py
"""
定义learning_logs的URL模式
"""
from django.urls import path
from . import views

app_name = 'learning_logs'
urlpatterns = [
    #主页
    path('', views.index, name='index'),
    #显示所有的主题
    path('topics/', views.topics, name='topics'),
    #显示特定主题的详细页面
    path('topics/<int:topic_id>/', views.topic, name='topic'),#topic_id的数值来自于topics中的遍历取id值
    #用于添加新主题的页面
    path('new_topic/', views.new_topic, name='new_topic'),
    #用于添加新条目的页面
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),#topic_id的数值来自于topics中的遍历取id值
    #用于编辑条目页面
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),#entry_id来自topic中的循环
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    #包含默认的身份认证url,包括login和logout。对于login：此为django默认的视图login，与http://localhost:8000/users/login匹配。其他类似。
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.数据库创建
class Topic(models.Model):
    '''用户学习的主题'''
    text=models.CharField(max_length=200)#文本
    date_added=models.DateTimeField(auto_now_add=True)#自动设置当前日期和时间
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        '''返回模型的字符串表示'''
        return self.text
        
class Enrty(models.Model):
    #学到的有关某个主题的知识
    topic=models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added=models.DateTimeField(auto_now_add=True)
    
    class  Meta:
        verbose_name_plural='entries'
    
    def __str__(self):
        #返回模型的字符串表示
        if len(self.text)>50:
            return  f'{self.text[:50]}...'
        else:
            return  f'{self.text[:50]}'

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic, Enrty

class TopicForm(forms.ModelForm):
    class Meta:
        model=Topic#topic models
        fields=['text']
        lables={'text':''}
        
class EntryForm(forms.ModelForm):
    class Meta:
        model = Enrty
        fields=['text']
        lables={'text': ' '}
        widgets={'text':forms.Textarea(attrs={'cols':80})}

learning_logs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import Http404
from .models import Topic, Enrty
from .forms import TopicForm, EntryForm

# Create your views here.

def index(request):
    #学习笔记的主页
    return render(request, 'learning_logs/index.html')
    
@login_required
def topics(request):
    #显示所有的主题
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics':topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    #显示单个主题以及其所有条目
    topic = get_object_or_404(Topic, id=topic_id)
    #确认请求的主题属于当前用户
    if topic.owner != request.user:
        raise Http404
    entries = topic.enrty_set.order_by('-date_added')
    context = {'topic': topic, 'entries':entries}
    #此处不是网址路径，而是文件存放路径
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    #添加新主题
    if request.method != 'POST':
    #未提交数据：创建一个新表单
        form = TopicForm()
    else:
    #POST提交的数据：对数据进行处理
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user#设置用户
            new_topic.save()#存入数据库
            return redirect('learning_logs:topics')
            
    context={'form':form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    #在特定主题中添加新条目
    topic = get_object_or_404(Topic, id=topic_id)
    #确认请求的主题属于当前用户
    if topic.owner != request.user:
        raise Http404
        
    if request.method != 'POST':
        #未提交数据：创建一个新表单
        form=EntryForm()
    else:
        #POST提交的数据：对数据进行处理
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry=form.save(commit=False)
            new_entry.topic=topic#设置主题
            new_entry.save()#存入数据库
            return redirect('learning_logs:topic', topic_id=topic_id)
            
    context={'topic':topic,'form':form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    #编辑既有的条目
    entry=get_object_or_404(Enrty, id=entry_id)
    topic = entry.topic
    #确认请求的主题属于当前用户
    if topic.owner != request.user:
        raise Http404
    
    if request.method != 'POST':
        #初次请求，使用当前条目填充表单
        form=EntryForm(instance=entry)
    else:
        #POST提交的数据：对数据进行处理
        form =EntryForm(instance=entry,data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)
    
    context={'entry':entry,'topic':topic,'form':form}
    return render(request, 'learning_logs/edit_entry.html', context)
    

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def register(request):
    #注册新用户
    if request.method != 'POST':
        #显示空的注册表单
        form = UserCreationForm()
    else:
        #处理填写好的表单
        form=UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user=form.save()
            #让用户自动登录，再重定向到主页
            login(request, new_user)
            return redirect('learning_logs:index')
            
    #显示空表单或指出表单无效
    context={'form':form}
    return render(request, 'registration/register.html', context)
        

learning_logs/templates/learning_logs/base.html
{%load bootstrap4%}

<!doctype html>
<html lang='en'>
<head>
  <meta charset='utf-8'>
  <meta name='viewport' content='width=device-width, initial-scale=1,shrink-to-fit=no'>
  <title>Learning Log</title>
  
  {%bootstrap_css%}
  {%bootstrap_javascript jquery='full'%}
</head>

<body>
  <nav class='navbar navbar-expand-md navbar-light bg-light mb-4 border'>
    <a href="{%url 'learning_logs:index'%}" class='navbar-brand'>生活笔记</a>
	<button class='navbar-toggler' type='button' 
	data-toggle='collapse' data-target='#navbarCollapse' aria-controls='navbarCollapse' aria-expand='false' aria-lable='Toggle navigation'>
	<span class='navbar-toggler-icon'></span></button>
	
    <div class='collapse navbar-collapse' id='navbarCollapse'>
      <ul class='navbar-nav mr-auto'>
	    <li class='nav-item'>
	      <a class='nav-link' href="{%url 'learning_logs:topics'%}">主题</a></li>
	  </ul>
	
	  <ul class='navbar-nav ml-auto'>
	    {%if user.is_authenticated%}
	    <li class='nav-item'>
	      <span class='navbar-text'>你好, {{user.username}}~ </span></li>
	    <li class='nav-item'>
	      <a class='nav-link' href="{%url 'users:logout'%}">注销</a></li>
        {%else%}
	    <li class='nav-item'>
	      <a class='nav-link' href="{%url 'users:register'%}">注册</a></li>
	    <li class='nav-item'>
	      <a class='nav-link' href="{%url 'users:login'%}">登录</a></li>
    {%endif%}
	  </ul>
    </div>
	
  </nav>
  
  <main role='main' class='container'>
    <div class='pb-2 mb-2 border-bottom'>
	  {%block page_header%}{%endblock page_header%}
	</div>
	<div>
	  {%block content%}{%endblock content%}
	</div>
  </main>
  
</body>

</html>

learning_logs/templates/learning_logs/edit_entry.html
{%extends "learning_logs/base.html"%}

{%block page_header%}
  <h3><a href="{%url 'learning_logs:topic' topic.id%}">{{topic}}</a></h3>
{%endblock page_header%}

{%block content%}

  <div class='jumbotron'>
    <h5 class='display-5'>编辑条目：</h5>
	<form action = "{%url 'learning_logs:edit_entry' entry.id%}" method='post'>
      {%csrf_token%}
      {{form.as_p}}
      <button name='submit' class='btn btn btn-primary'>保存</button>
    </form>
  </div>


{%endblock content%}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}


{% block page_header %}
  <div class='jumbotron'>
    <h1 class='display-5'>记录你的生活！</h1>
	<p></p>
	<p class='lead'>随时随地，记录生活</p>
	<p></p>

	{%if user.is_authenticated%}
	  <a class='btn btn-lg btn-primary' href="{%url 'learning_logs:topics'%}" role='button'>主题</a>
	{%else%}
	  <a class='btn btn-lg btn-primary' href="{%url 'users:register'%}" role='button'>注册 &raquo;</a>
	{%endif%}
  </div>
{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{%extends "learning_logs/base.html"%}

{%block page_header%}
  <h3><a href="{%url 'learning_logs:topic' topic.id%}">{{topic}}</a></h3>
{%endblock page_header%}


{%block content%}

  <div class='jumbotron'>
    <h5 class='display-5'>新增条目：</h5>
	<form action = "{%url 'learning_logs:new_entry' topic.id%}" method='post'>
      {%csrf_token%}
      {{form.as_p}}
      <button name='submit' class='btn btn btn-primary'>新增</button>
    </form>
  </div>

{%endblock content%}

learning_logs/templates/learning_logs/new_topic.html
{%extends "learning_logs/base.html"%}

{%block page_header%}
  <h3>新增主题：</h3>
{%endblock page_header%}


{%block content%}

  <div class='jumbotron'>
	<form action = "{%url 'learning_logs:new_topic'%}" method='post' class='form'>
      {%csrf_token%}
      {{form.as_p}}
      <button name='submit' class='btn btn btn-primary'>新增</button>
    </form>
  </div>

{%endblock content%}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{%block page_header%}
  <h3>{{topic}}</h3>
{%endblock page_header%}

{%block content%}
  <p>
    <a href="{%url 'learning_logs:new_entry' topic.id%}">新增条目</a>
  </p>
  
  {%for entry in entries%}
    <div class='card mb-3'>
	  <h5 class='card-header'>
	    {{entry.date_added|date:'M d, Y H:i'}}
	    <small><a href="{%url 'learning_logs:edit_entry' entry.id%}">编辑</a></small>
	  </h5>
      <div class='card-body'>
	    {{entry.text|linebreaks}}
	  </div>
    </div>
  {%empty%}
    <p>当前主题无任何条目。</p>
  {%endfor%}
  
{%endblock content%}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{%block page_header%}
  <h2>主题</h2>
{%endblock page_header%}


{%block content%}
  <p>
    <a href="{%url 'learning_logs:new_topic'%}">新增主题</a>
  </p>
  <ul>
    {%for i in topics%}
	  <li><h4>
	    <a href="{% url 'learning_logs:topic' i.id%}">{{i}}</a>
	  </h4></li>
	{%empty%}
	  <li><h4>当前无任何主题。</h4></li>
	{%endfor%}
  </ul>
  
{%endblock content%}